extends: default

rules:
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  indentation:
    spaces: 2
  truthy:
    check-keys: false
  braces:
    max-spaces-inside: 10
  document-start: disable
  new-line-at-end-of-file: disable
  new-lines: disable
